# OpenSea Key
opensea_key: "" # Opensea key

# Dictionary with collection_name : FP - [lower, upper]
nft_collections:
  'memelandcaptainz': [2.5, 4.2]
  'treeverse-plots': [0.2, 0.4]

crypto_currency:
  'MEME': [0.02, 0.04]
  'ETH': [3000, 4300]

# Mailing setup
send_analytics: True # If True, send email when FP is surpassed
# App password (https://support.google.com/accounts/answer/185833?hl=en)