# Dictionary with collection_name : FP - [lower, upper]
nft_collections:
  'memelandcaptainz': [3.0, 3.7]
  'thepotatoz': [1.2, 1.6]

crypto_currency:
  'MEME': [0.02, 0.03]
  'ETH': [3000, 4300]

# Mailing setup
send_analytics: True # If True, send email when FP is surpassed
# App password (https://support.google.com/accounts/answer/185833?hl=en)