# Dictionary with collection_name : FP - [lower, upper]
nft_collections:
  'memelandcaptainz': [2.0, 3.0]

crypto_currency:
  'MEME': [0.01, 0.02]

# Mailing setup
send_analytics: True # If True, send email when FP is surpassed
# App password (https://support.google.com/accounts/answer/185833?hl=en)