# OpenSea Key
opensea_key: "6cabe496f87d49b48869406c398f2af7"

# Collection properties
nft_collections:
  'thepotatoz': 1.6
  'thecaptainz': 4.9

# Mailing setup
send_analytics: True
sender_password: "evvbfzpeusmyicit"
sender_mail: "pythonlovesfinance@gmail.com"
receiver_mail: "ericmatamoros1999@gmail.com"